// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRULs-S5ZLE7-d03JYF88i2H5Jol6Q1HU',
    appId: '1:229712878962:web:99ac8525697a3fcad691eb',
    messagingSenderId: '229712878962',
    projectId: 'pawpoints-298c1',
    authDomain: 'pawpoints-298c1.firebaseapp.com',
    storageBucket: 'pawpoints-298c1.firebasestorage.app',
    measurementId: 'G-9BTGY31LYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmcIEdkUwsjtfIyY-ruWHFlhXY6-vzdnI',
    appId: '1:229712878962:android:8d59384bd39cbe25d691eb',
    messagingSenderId: '229712878962',
    projectId: 'pawpoints-298c1',
    storageBucket: 'pawpoints-298c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgtMb84qc-jAo4AZk0guIEN55nuY63Jcs',
    appId: '1:229712878962:ios:c510d0a027adb810d691eb',
    messagingSenderId: '229712878962',
    projectId: 'pawpoints-298c1',
    storageBucket: 'pawpoints-298c1.firebasestorage.app',
    iosBundleId: 'com.example.pawpoints',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgtMb84qc-jAo4AZk0guIEN55nuY63Jcs',
    appId: '1:229712878962:ios:c510d0a027adb810d691eb',
    messagingSenderId: '229712878962',
    projectId: 'pawpoints-298c1',
    storageBucket: 'pawpoints-298c1.firebasestorage.app',
    iosBundleId: 'com.example.pawpoints',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRULs-S5ZLE7-d03JYF88i2H5Jol6Q1HU',
    appId: '1:229712878962:web:5a88ce1cc78b0abfd691eb',
    messagingSenderId: '229712878962',
    projectId: 'pawpoints-298c1',
    authDomain: 'pawpoints-298c1.firebaseapp.com',
    storageBucket: 'pawpoints-298c1.firebasestorage.app',
    measurementId: 'G-HJY499D7Q2',
  );
}